### ISSUE TITLE
[QUESTION] May we use with one parameter?

### ISSUE THREAD

**Issue by Sentence** [Gregwar/ImageBundle#106]
May we use one parameter instead of 2?

e.g.:
`{{ image('linux.jpg').resize(100)}}`

It's seems to be work, but I need a confirmation. 😃 (I don't have time to gather from code.)

Regards!

**Comment by Soullivaneuh** [comment]
Yes: https://github.com/Gregwar/Image/blob/c506d57d7fb5e67961d4eea6540ae8e23dffd406/Image.php#L17-L20
