### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by pasqualepalmaccio** [Gregwar/ImageBundle#110]
Bundle not currently supported by Symfony 4. Can you fix ?

**Comment by rawburner** [comment]
Need S4 support please!

**Comment by ggabrovski** [comment]
For the moment you can use this Fork: arkounay/gregwar-image-bundle
https://packagist.org/packages/arkounay/gregwar-image-bundle
Support S4

**Comment by Gregwar** [comment]
I integrated the changes from @arkounay 's fork and tagged `v2.2.2`, can you confirm me it's ok?

**Comment by Arkounay** [comment]
Thanks @Gregwar and @Sentence, I've tested this new `2.2.2` version on both Symfony 3 and 4 apps and everything worked perfectly here 👍

**Comment by ggabrovski** [comment]
Thanks, everything worked great

**Comment by Gregwar** [comment]
Ok, thanks for contributing and sorry for the delay
