### ISSUE TITLE
Deprecation error on Symfony 4.2 and up

### ISSUE THREAD

**Issue by Thorry84** [Gregwar/ImageBundle#116]
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

Maybe something to look at? I've seen a lot of packages have this problem.

Originally posted incorrectly: https://github.com/Gregwar/Image/issues/157

https://github.com/Gregwar/ImageBundle/blob/0024f16805cc3cf123ae4ac70ade1dd39eccc103/DependencyInjection/Configuration.php#L18

**Comment by Zausenec** [comment]
#118
