### ISSUE TITLE
Save doesn't work if merge is applied

### ISSUE THREAD

**Issue by alainmf** [Gregwar/ImageBundle#35]
Hello, 

I am using Gregwar/ImageBundle for my Symfony 2.3 under PHP v5.4.19 project and all the methods work (negate, save, sepia, etc) but once I use the merge() method it doesn't seem to work. Whenever I use the merge method it automatically falls back on to the fallback image....

Please help. Does anyone know why this could be happening ? 

Thanks
Alain

Here is my code. 

$logo = $this->get('image.handling')->open('img/logo.jpeg');
$imagez = $this->get('image.handling')->open('feeds/' . $url); 
$imagez->merge($logo, 10, 10, 50, 50); 
$imagez->save('img/outout/out200.jpeg', 'jpeg', 100);

**Comment by Renjyy** [comment]
Hi, 
same case, same problem in here ! @alainmf Which version of the bundle you used in the end ?

**Comment by Renjyy** [comment]
Sorry, didnt read the documentation properly : the merge function 1st parameter expects an instance of Gregwar's Image to work properly

Thanks !
