### ISSUE TITLE
Tag the current release as stable

### ISSUE THREAD

**Issue by snamor** [Gregwar/ImageBundle#99]
May you tag the current release with a version number? We are using your bundle in some projects with Symfony 3 and we have to use dev-master as the latest stable release is not working with Symfony 3. It would be great if we could use a version instead of dev-master.

Thanks!

**Comment by Gregwar** [comment]
Tagged `v2.1.1`, is it OK for youN

**Comment by snamor** [comment]
Works like a charm! Thank you for your swiftness!
